version: '3'

services:
  redis:
      image: redis:latest
      ports:
        - "6379:6379"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./Database:/app/Database
      - ./logs:/app/logs
    restart: always  
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    restart: always  