version: '3.8'

services:
  redis:
      image: redis:latest
      # ports:
      #   - "6379:6379"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./Database:/app/Database
      - ./logs:/app/logs
      - static_volume:/app/static
    restart: always  
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/static
    depends_on:
      - web
    restart: always  

volumes:
  static_volume: