version: '3.8'

services:
  redis:
      image: redis:latest
      # ports:
      #   - "6379:6379"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./Database:/app/Database
      - ./logs:/app/logs
      - ./static:/app/static
    ports:
      - 8000:80
    restart: always  
    depends_on:
      - redis